plugins {
    id 'java'
    id("org.jetbrains.kotlin.jvm") version "2.2.0"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.2.0"
}

group 'nion.network'
version '0.1'
//configurations.implementation.setCanBeResolved(true)

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.2")


    implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0')
    implementation('org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.3.0')
    implementation('org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0')
    implementation("com.influxdb:influxdb-client-kotlin:7.3.0")
    implementation('org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2-native-mt')
}

test {
    useJUnitPlatform()
    scanForTestClasses = false
    failOnNoDiscoveredTests = false
}
tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes.put("Main-Class", "LaunchKt")
    }
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath
                .collect { it.isDirectory() ? it : zipTree(it) }
    })
}